In [4]:
# SWASTIK SHARMA 102203231
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

train_df = pd.read_csv("data.csv")
test_df = pd.read_csv("test.csv")

y_train = train_df['label']
x_train = train_df.drop('label', axis=1)
x_test = test_df

test_sizes = [0.4, 0.3, 0.25, 0.2, 0.1, 0.05]

k_values = [2, 4, 5, 6, 7, 10]

results = {}

for test_size in test_sizes: 
    x_train_split, x_val, y_train_split, y_val = train_test_split(x_train, y_train, test_size=test_size, random_state=40)
    
    scaler = StandardScaler()
    scaler.fit(x_train_split)
    x_train_split = scaler.transform(x_train_split)
    x_val = scaler.transform(x_val)
    x_test_scaled = scaler.transform(x_test)
    
    for k in k_values:
        classifier = KNeighborsClassifier(n_neighbors=k)
        classifier.fit(x_train_split, y_train_split)
        
        y_pred_val = classifier.predict(x_val)
        
        accuracy_val = accuracy_score(y_val, y_pred_val)
        cm = confusion_matrix(y_val, y_pred_val)
        
        results[(test_size, k)] = {'Validation Accuracy': accuracy_val, 'Confusion Matrix': cm}

    for params, metrics in results.items():
        print("Test Size: {}\t K: {}\n".format(params[0], params[1]))
        print("Validation Accuracy: {}\n".format(metrics['Validation Accuracy']))
        print("Confusion Matrix:\n{}\n".format(metrics['Confusion Matrix']))
        print("-----------------------------------\n")


Test Size: 0.4	 K: 2

Validation Accuracy: 0.9167857142857143

Confusion Matrix:
[[1596    0    3    3    2    5    7    0    0    1]
 [   1 1863    3    0    0    1    0    0    2    1]
 [  27   28 1596   22    7    2    9   12    7    3]
 [   8   11   56 1679    2   22    1    9   11    4]
 [   2   35   20    3 1535    3    4   12    2   26]
 [  13    5    6  100    9 1340   19    7    5    2]
 [  42    4   16    1    6   24 1518    0    1    0]
 [   3   29   19   17   31    1    0 1616    1   35]
 [  18   25   32   71   29  105    6   11 1275   16]
 [  10   12    9   25   95   13    0  137   11 1384]]

-----------------------------------

Test Size: 0.4	 K: 4

Validation Accuracy: 0.9288095238095239

Confusion Matrix:
[[1587    0    2    4    0    6   13    2    1    2]
 [   1 1860    3    0    0    1    3    1    1    1]
 [  18   30 1593   21    9    1   12   15    9    5]
 [   5   10   29 1682    1   27    2   18   19   10]
 [   1   34   14    4 1525    6    4    8    2   44]
 [  